# Jykell configuration
#markdown: redcarpet
#highlighter: pygments
language: 'kr'

# Website info
name: kjuhee's blog
title: kjuhee's blog
description: "행복한 사람으로 살기"
avatar: https://kjuhee0712.github.io/jhblog/assets/images/logo.png
email: kjuhee0712@gmail.com 
baseurl: /jhblog/
paginate: 50
paginate_path: "/jhblog/blog/page-:num"


# Author's info
author: 'kjuhee'
nickname: juhee
location: 'seoul, KOREA'
url: 'http://kjuhee0712.github.io/jhblog/'
image: 'assets/images/logo.png'
default_img: assets/images/logo.png
profile_img: assets/images/logo.png
# edit 'categories' in the front matter of every post to match this username
# bio: 

short_url: 'kjuhee0712.github.io/jhblog/'
disqus: Kjuhee
# google_analytics: UA-69281367-1
# edit baseurl to simply '/' if using as your personal page (instead of a project page)

# Permalinks
permalink: /:year/:month/:day/:title/

# Build settings
include: ["_categories", "_tags"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
syntax_highlighter: rouge
syntax_highlighter_opts:
# Use existing pygments syntax highlighting css
css_class: 'highlight'

# Sass
sass:
  style: expanded

# gems and other configs
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]

safe: false
lsi: false
repo: jhblog
branch: master
relative_source: ../jhblog/
destination: ../jhblog-pages/
production_url:  https://kjuhee0712.github.io/jhblog/
source_url:      https://github.com/kjuhee0712/jhblog/
